module.exports = Object.freeze({

    HOSPITALITY: "HOSPITALITY",

    RETAIL: "RETAIL",

    TRANSPORT: "TRANSPORT",

    AVIATION: "AVIATION",

    CONSTRUCTION: "CONSTRUCTION",

    ENGINEERING: "ENGINEERING",

    TECHNOLOGY: "TECHNOLOGY",

    HEALTHCARE: "HEALTHCARE",

    EMERGENCY_SERVICES: "EMERGENCY_SERVICES",

    EDUCATION: "EDUCATION",

    FINANCE: "FINANCE",

    LAW: "LAW",

    SCIENCE: "SCIENCE",

    BUSINESS: "BUSINESS",

    AGRICULTURE: "AGRICULTURE",

    MEDIA: "MEDIA",

    GOVERNMENT: "GOVERNMENT",

    MILITARY: "MILITARY"

});