module.exports = Object.freeze({

    LICENCE: "LICENCE",

    BACKGROUND_CHECK: "BACKGROUND_CHECK",

    SECURITY_CLEARANCE: "SECURITY_CLEARANCE",

    PROFESSIONAL_REGISTRATION: "PROFESSIONAL_REGISTRATION",

    GOVERNMENT: "GOVERNMENT",

    HEALTH_AND_SAFETY: "HEALTH_AND_SAFETY",

    TRANSPORT: "TRANSPORT",

    FIRE_SAFETY: "FIRE_SAFETY",

    FOOD_SAFETY: "FOOD_SAFETY",

    FIRST_AID: "FIRST_AID"

});